// <auto-generated />
namespace WebSiteBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addrequiredNV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequiredNV));
        
        string IMigrationMetadata.Id
        {
            get { return "201905261244304_add-required-NV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
