// <auto-generated />
namespace WebSiteBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Twocolumn_Giamgia_And_Diemtichluy_For_DatHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Twocolumn_Giamgia_And_Diemtichluy_For_DatHang));
        
        string IMigrationMetadata.Id
        {
            get { return "201906111030378_Add_Twocolumn_Giamgia_And_Diemtichluy_For_DatHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
